# Project info
title:      How To
logo:       img/question.svg
copyright:  '&copy; 2016 05Bit'

# Data structure
chapters:
  # Main chapters
  - index:            index.md
    input_path:       .

# Rendering
output:
  html:
    build_path: ..
    theme:
      icons: awesome
    main_menu: []
resources:  ./_resources
templates:  ./_templates

# Serving html
server:
  host:       127.0.0.1
  port:       8080
  base_url:   /
  assets_url: assets/
